name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NODE_ENV: ci
  CI: true
jobs:
  build-client:
    name: Build Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install:client
      - name: Build
        run: yarn build:client

  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "16.14"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install:server
      - name: Build
        run: yarn build:server
